---
- name: Deploy Mautic and NGINX Containers
  hosts: localhost
  tasks:
    - name: Pull the Mautic Docker image
      community.docker.docker_image:
        name: mautic/mautic:latest
        source: pull

    - name: Pull the NGINX Docker image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Create a Docker network
      community.docker.docker_network:
        name: mautic_network
        driver: bridge

    - name: Start the Mautic container
      community.docker.docker_container:
        name: mautic
        image: mautic/mautic:latest
        state: started
        restart_policy: always
        networks:
          - name: mautic_network
        ports:
          - "8080:80"
        env:
          MYSQL_HOST: db
          MYSQL_DATABASE: mautic
          MYSQL_USER: mauticuser
          MYSQL_PASSWORD: mauticpassword

    - name: Create NGINX configuration for Mautic
      copy:
        dest: /vagrant/nginx.conf
        content: |
          server {
              listen 80;
              server_name mautic.local;

              location / {
                  proxy_pass http://mautic:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Start the NGINX container
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        networks:
          - name: mautic_network
        ports:
          - "80:80"
        volumes:
          - "/vagrant/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
